// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cxrlytcsoyfkevoewkvk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN4cmx5dGNzb3lma2V2b2V3a3ZrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAzODg3NjYsImV4cCI6MjA1NTk2NDc2Nn0.fQwJIQyuJhe8dGFCzaV5XPALeD3fZrHB_rXajqTosLs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);